assignments/urls.py
from django.urls import path 
from . import views

app_name = 'assignments'

urlpatterns = [
    path('<int:pk>/view-grades/', views.view_grades, name='view_grades'),
    path('<int:pk>/grade/', views.grade, name='grade'),
    path('<int:pk>/analyze/', views.analyze, name='analyze'),
]

finecode/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('comments', include('comments.urls')),
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
    path('', include('landingpage.urls')),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('assignments/', include('assignments.urls')),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(
        template_name = 'users/password_reset.html'),
        name = 'password_reset'
    ),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'),
        name = 'password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
    ),
        name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
    ),
      name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path 
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/<int:pk>/', views.create_post, name='create_post'),
    path('analyze/', views.analyze, name='analyze')
]

assignments/models.py
from django.db import models

# Create your models here.

assignments/forms.py
from django.forms import ModelForm
from django import forms

class GradeStudentForm(forms.Form):
    grade = forms.IntegerField(min_value=0,max_value =100)

assignments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from posts.models import SubmittedAssignment,Assignment
from classroom.models import Classroom
from comments.forms import PrivateCommentForm
from .forms import GradeStudentForm

@login_required
def view_grades(request,pk):
    assignment = get_object_or_404(Assignment,pk=pk)
    submitted_assignments = assignment.submittedassignment_set.all()
    context = {
        'submitted_assignments':submitted_assignments,
        'assignment':assignment,
    }
    return render(request, 'assignments/view_grades.html', context)

@login_required
def grade(request,pk):
    submit_assignment = get_object_or_404(SubmittedAssignment, pk=pk)
    if request.method == 'POST':
        grade_form = GradeStudentForm(request.POST)
        if grade_form.is_valid():
            grade = grade_form.cleaned_data.get('grade')
            submit_assignment.is_reviewed = True
            submit_assignment.grade = grade 
            submit_assignment.save()
        else:
            print('not valid')
    else:
        grade_form = GradeStudentForm() 
            
    assignment_files = submit_assignment.assignmentfile_set.all()
    # print(assignment_files)
    context = {
        'submit_assignment':submit_assignment,
        'assignment_files':assignment_files,
        'grade_form':grade_form,
    }
    return render(request, 'assignments/grade.html', context)

@login_required
def analyze(request,pk):
    assignment = get_object_or_404(Assignment, pk=pk)
    submit_assignment = get_object_or_404(SubmittedAssignment, pk=pk)
    assignment_files = submit_assignment.assignmentfile_set.all()

    context = {
        'submit_assignment':submit_assignment,
        'assignment_files':assignment_files,
        'assignment':assignment,
    }
    
    return render(request, 'assignments/analyze.html', context)

assignments/templates/assignments/analyze.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
</head>
<body>
     <div class="row">
          {% for ass in assignment.submitted_assignments %}
          <img src="{{ ass.user.profile.image.url }}" width="35" height="35" alt="..." class="rounded-circle mr-2 mb-2 float-left">
          <p class="pt-2">{{ submit_assignment.user.first_name }} {{submit_assignment.user.last_name}}</p>
          {% endfor %}
     {{assignment_files}}
     {% for file in assignment_files %}
     <h5 class="card-title">{{ file.filename }}</h5>
     {{ file.files.url }}
     {% endfor %}
</body>
</html>

assignments/templates/assignments/grade.html
{% extends 'assignment_base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} Assignment-Create {% endblock title %}

{% block content %}
<nav class="navbar navbar-light bg-light">
    <div class="navbar-brand">
        <a href="{% url 'assignments:view_grades' submit_assignment.assignment.pk %}"><i class="fas fa-times"></i></a>
        <div class="pl-3 float-right">Grade <strong>{{ submit_assignment.user.username }}</strong> for <strong>{{ submit_assignment.assignment.title }}</strong></div>
    </div>
    <!-- <form class="form-inline">
        <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
            <button type="button" class="btn btn-primary">Return</button>
            
            <div class="btn-group" role="group">
                <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                    <a class="dropdown-item" href="#">Dropdown link</a>
                    <a class="dropdown-item" href="#">Dropdown link</a>
                </div>
            </div>
        </div>
    </form> -->
</nav>

<div class="container-fluid">
    <!-- Make a form here -->
    <div class="row m-3">
        <div class="col-lg-9">
            <div class="row">
                {% for file in assignment_files %}
                <a target="_blank" href="{{ file.files.url }}">
                    <div class="col-4">
                        <div class="card border border-secondary" style="width: 18rem;">
                            <img class="card-img-top" src="{{ file.files.url }}">
                            <div class="card-body">
                              <h5 class="card-title">{{ file.filename }}</h5>
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
        <!-- The selection stuff -->
        <div class="col-lg-3 vl v p-3 mt-sm-2">
            <!-- For -->
            <hr class='d-lg-none d-sm-block'>
            <h5><strong>Grade {{ submit_assignment.user.first_name }} {{submit_assignment.user.last_name}}</strong></h5>
            <h5><strong>Grade : 
                {% if submit_assignment.is_reviewed %}
                    {{ submit_assignment.grade }}
                {% else %}
                    Not graded
                {% endif %}
            </strong></h5>
                <form action="" method="POST">
                {% csrf_token %}
                {{ grade_form|crispy }}
                <button class="btn btn-primary float-right">Grade</button>
            </form>

        </div>

    </div>
</div>
<!-- /.container-fluid -->
{% endblock %}

assignments/templates/assignments/view_grades.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} View Grades {% endblock title %}

{% block content %}

<div class="card  bg-white border-0">
    <div class="card-body">
        <h5 class="card-title">{{ assignment.title }}</h5>
        <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>Username</th>
                <th>
                        Out Of {{ assignment.marks }}
                        <a class="btn btn-circle float-right" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-dark"></i>
                        </a>			
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                        </div>
                </th>
                <th>
                    View
                </th>
            </tr>
            </thead>

            <tbody>
                {% for submitted_assignment in submitted_assignments %}
                <tr>
                    <td>{{ submitted_assignment.user.username }}</td>
                    <td>
                        {% if submitted_assignment.is_reviewed %}
                            {{ submitted_assignment.grade }}
                        {% else %}
                            Ungraded
                        {% endif %}
                        </td>
                    <td><a class="stretched-link" href="{% url 'assignments:grade' submitted_assignment.pk %}">View</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock content %}