assignments/urls.py
from django.urls import path 
from . import views

app_name = 'assignments'

urlpatterns = [
    path('<int:pk>/view-grades/', views.view_grades, name='view_grades'),
    path('<int:pk>/grade/', views.grade, name='grade'),
    path('<int:pk>/analyze/', views.analyze, name='analyze'),
]

classroom/urls.py
from django.urls import path 
from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create_classroom, name = 'create_classroom'),
    path('join/', views.join_classroom, name = 'join_classroom'),
    path('open/<int:pk>/', views.open_classroom, name = 'open_classroom'),
    path('<int:pk>', views.delete_classroom, name = 'delete_classroom'),
    path('<int:pk>/members', views.members, name = 'members_classroom'),
    path('assignment/<int:pk>/student_work', views.student_work, name = 'student_work'),
    path('assignment/create', views.assignment_create, name = 'assignment_create'),
    path('assignment/<int:pk>', views.assignment_submit, name = 'assignment_submit'),
    path('assignment/<int:pk>/turnin/', views.turnin, name = 'turnin'),
    path('assignment/<int:pk>/unsubmit/', views.unsubmit, name = 'unsubmit'),
    path('assignment/<int:pk>/unsubmit_file/', views.unsubmit_file, name = 'unsubmit_file'),
    path('todo/', views.todo, name = 'todo'),
    path('toreview/', views.toreview, name = 'toreview'),
    path('<int:pk>/classwork/', views.classwork, name = 'classwork'),
    path('analyze/', views.analyze, name='analyze')
]

comments/urls.py
from django.urls import path,include
from . import views

app_name='comments'

urlpatterns = [
    path('comment/create/<int:post_pk>/', views.create_comment, name='create_comment'),
    path('privatecomment/create/<int:assignment_pk>/', views.create_private_comment, name='private_comment'),
]

finecode/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('comments', include('comments.urls')),
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
    path('', include('landingpage.urls')),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('assignments/', include('assignments.urls')),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(
        template_name = 'users/password_reset.html'),
        name = 'password_reset'
    ),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'),
        name = 'password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
    ),
        name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
    ),
      name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path 
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/<int:pk>/', views.create_post, name='create_post'),
    path('analyze/', views.analyze, name='analyze')
]

classroom/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# members are not teachers
class Classroom(models.Model):
    name = models.CharField(max_length=200)
    classroom_code = models.CharField(max_length=20, blank=True)
    description = models.TextField(max_length=300)
    slug = models.SlugField(max_length=250,unique_for_date='created_at')
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(default=timezone.now)
    users = models.ManyToManyField(User,related_name='users')
    
    def __str__(self):
        return f'{self.name}'


# Memebers in this table are onl the teachers 
class ClassroomTeachers(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.teacher.username} -> {self.classroom.name}'


class Topic(models.Model):
    name = models.CharField(max_length=200)
    classroom = models.ForeignKey(Classroom,on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.classroom.name} -> {self.name}'
    

classroom/forms.py
from django.forms import ModelForm
from django import forms
from  .models import Classroom,Topic

class ClassroomCreationForm(ModelForm):
    class Meta:
        model = Classroom
        fields = ['name', 'description']

class JoinClassroomForm(forms.Form):
    code = forms.CharField(label='Enter Code', max_length=100)

class PostForm(forms.Form):
    title = forms.CharField()
    description = forms.CharField(widget=forms.Textarea)
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class AssignmentFileForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class AssignmentCreateForm(forms.Form):
    def __init__(self,user,*args, **kwargs):
        super(AssignmentCreateForm, self).__init__(*args,**kwargs)
        classrooms = list(map(lambda x: x.classroom, user.classroomteachers_set.all()))
        topics = []
        self.fields['classrooms'].choices = [(str(classroom.pk),classroom.name) for classroom in classrooms]
        for classroom in classrooms:
            topics.extend(list(classroom.topic_set.all()))
        self.fields['topics'].choices = [(str(topic.pk),f"{topic.name}->{topic.classroom.name}") for topic in topics]

    title = forms.CharField()
    description = forms.CharField(widget=forms.Textarea)
    classrooms = forms.ChoiceField()
    topics = forms.ChoiceField()
    points = forms.IntegerField(min_value=0,max_value =100)
    due_date = forms.DateTimeField()
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True})) 

classroom/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required


from .models import Classroom,Topic,ClassroomTeachers
from posts.models import Assignment,SubmittedAssignment,AssignmentFile, Attachment
from .forms import ClassroomCreationForm,JoinClassroomForm, PostForm, AssignmentFileForm, AssignmentCreateForm
from comments.forms import CommentCreateForm, PrivateCommentForm

@login_required
def home(requests):
    teaching_classes = set([classroom.classroom for classroom in requests.user.classroomteachers_set.all()])
    classrooms = set(requests.user.classroom_set.all()).union(teaching_classes)
    classroom_form = ClassroomCreationForm()
    join_classroom_form = JoinClassroomForm()
    context = {
        'classrooms' : classrooms,
        'classroom_form': classroom_form,
        'join_classroom_form':join_classroom_form
    }
    return render(requests, 'classroom/home.html', context)

@login_required
def create_classroom(request):
    if request.method == 'POST':
        print('fORM vaLID')
        form = ClassroomCreationForm(request.POST)
        if form.is_valid(): 
            name = form.cleaned_data.get('name')
            description = form.cleaned_data.get('description')
            classroom = Classroom(name=name, description=description, created_by=request.user)
            classroom.save()
            classroom.classroom_code = classroom.name[:4] + str(classroom.id)
            classroom.save()
            topic = Topic(name = 'General' , classroom = classroom)
            topic.save()
            classroom_teachers = ClassroomTeachers(classroom = classroom, teacher=request.user)
            classroom_teachers.save()
            messages.success(request, f'Classroom {name} created !')
        else:
            messages.danger(request, f'Classroom Could not be created :(')
    return redirect('classroom:home')

@login_required
def join_classroom(request):
    if request.method == 'POST':
        print('fORM vaLID')
        form = JoinClassroomForm(request.POST)
        if form.is_valid(): 
            classroom = Classroom.objects.filter(classroom_code = form.cleaned_data.get('code')).first()
            if classroom:
                request.user.classroom_set.add(classroom)
                messages.success(request, f'You are added in {classroom.name}')
            else:
                messages.success(request, f'Error adding you to the classroom')
        else:
            messages.success(request, f'Error adding you to the classroom')
    return redirect('classroom:home')

@login_required
def open_classroom(requests,pk):
    classroom = get_object_or_404(Classroom,pk = pk)
    topics = classroom.topic_set.all()
    contents = []
    for topic in topics:
        contents.extend(list(topic.post_set.all()))
        contents.extend(list(topic.assignment_set.all()))
    
    contents.sort(key = lambda x: x.created_at)

    post_form = PostForm()
    comment_form = CommentCreateForm()

    context = {
        'classroom' : classroom,
        'contents': reversed(contents),
        'post_form': post_form,
        'comment_form': comment_form,
    }

    return render(requests, 'classroom/classroom.html', context)

@login_required
def delete_classroom(requests):
    context = {
        'title' : 'Classroom',
    }
    return render(requests, 'base.html', context)


@login_required
def members(request, pk):
    classroom = get_object_or_404(Classroom, pk=pk)
    context = {
        'teachers': classroom.classroomteachers_set.all(),
        'students': classroom.users.all(),
    }
    return render(request, 'classroom/members.html', context)

@login_required
def assignment_create(request):
    if request.method == 'POST':
        form = AssignmentCreateForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            topic = get_object_or_404(Topic, pk=int(form.cleaned_data['topics']))
            assignment = Assignment(
                title = form.cleaned_data['title'],
                description = form.cleaned_data['description'],
                created_by = request.user,
                topic = topic,
                due_date = form.cleaned_data['due_date']
            )
            assignment.save()
            files = request.FILES.getlist('file_field')
            for f in files:
                Attachment.objects.create(assignment = assignment,files=f)
            return redirect('classroom:open_classroom', topic.classroom.pk)

    else:
        form = AssignmentCreateForm(request.user)
    context = {'form':form}
    return render(request, 'classroom/assignment_create.html', context)


@login_required
def assignment_submit(request, pk):
    if request.method=='POST':
        assignment = get_object_or_404(Assignment,pk=pk)
        submitted_assignment = assignment.submittedassignment_set.filter(user = request.user).first()
        if not submitted_assignment:
            submitted_assignment = SubmittedAssignment.objects.create(assignment = assignment, user = request.user)
        files = request.FILES.getlist('file_field')
        print(files)
        for f in files:
            AssignmentFile.objects.create(submitted_assignment = submitted_assignment,files=f)
    
    form = AssignmentFileForm()
    private_comment_form = PrivateCommentForm()
    assignment = get_object_or_404(Assignment, pk=pk)
    submit_assignment = assignment.submittedassignment_set.filter(user=request.user)
    classroom_teachers = list(map(lambda teaches: teaches.teacher, assignment.topic.classroom.classroomteachers_set.all()))
    print(classroom_teachers)
    is_teacher = request.user in classroom_teachers
    print(is_teacher)
    if submit_assignment:
        submit_assignment = submit_assignment.first()
        assignment_files = submit_assignment.assignmentfile_set.all()
    else: assignment_files = None


    context = {
        'assignment': assignment,
        'attachments': assignment.attachment_set.all(),
        'submitted_assignment': submit_assignment,
        'assignment_files': assignment_files,
        'form':form,
        'private_comment_form': private_comment_form,
        'is_teacher': is_teacher,
    }
    return render(request, 'classroom/assignment_submit.html', context)

@login_required
def turnin(request,pk):
    if request.method == 'POST':
        assignment = get_object_or_404(Assignment,pk=pk)
        submitted_assignment = assignment.submittedassignment_set.filter(user = request.user).first()
        if not submitted_assignment:
            submitted_assignment = SubmittedAssignment.objects.create(assignment = assignment, user = request.user)
        submitted_assignment.turned_in = True 
        submitted_assignment.save()
        
    return redirect('classroom:assignment_submit', pk)

@login_required
def unsubmit(request,pk):
    if request.method == 'POST':
        assignment = get_object_or_404(Assignment,pk=pk)
        submitted_assignment = assignment.submittedassignment_set.filter(user = request.user).first()
        submitted_assignment.turned_in = False  
        submitted_assignment.save()
        
    return redirect('classroom:assignment_submit', pk)

@login_required
def unsubmit_file(request, pk):
    if request.method == 'POST':
        assignment_file = get_object_or_404(AssignmentFile, pk=pk)
        assignment_pk = assignment_file.submitted_assignment.assignment.pk
        if assignment_file.submitted_assignment.user == request.user:
            if assignment_file.submitted_assignment.turned_in:
                submitted_assignment = assignment_file.submitted_assignment
                submitted_assignment.turned_in = False  
                submitted_assignment.save()
            assignment_file.delete()
        return redirect('classroom:assignment_submit', assignment_pk)

@login_required
def todo(request):
    classrooms = request.user.classroom_set.all()
    topics = []
    for classroom in classrooms:
        topics.extend(list(classroom.topic_set.all()))
    assignments = []
    for topic in topics:
        assignments.extend(list(topic.assignment_set.all()))
    filtered_assignment = []
    for assignment in assignments:
        if not assignment.is_turnedin(request.user):
            filtered_assignment.append(assignment)
    context = {'assignments':filtered_assignment}
    
    return render(request, 'classroom/todo.html', context)




@login_required
def toreview(request):
    classrooms = request.user.classroomteachers_set.all()
    classrooms = list(map(lambda x: x.classroom, classrooms))
    topics = []
    for classroom in classrooms:
        topics.extend(classroom.topic_set.all())
    assignments = []
    for topic in topics:
        assignments.extend(topic.assignment_set.all())
    context = {'assignments': reversed(assignments)}
    return render(request, 'classroom/toreview.html', context)


@login_required
def classwork(request, pk):
    classroom = get_object_or_404(Classroom,pk=pk)
    assignments = []
    for topic in classroom.topic_set.all():
        assignments.extend(list(topic.assignment_set.all()))
    
    context = {'assignments':assignments}
    return render(request, 'classroom/classwork.html', context)

def student_work(request, pk):
    assignment = get_object_or_404(Assignment, pk=pk)
    context = {'assignment': assignment}
    return render(request, 'classroom/student_work.html', context)


import os
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def analyze(request):
    from .codes import test
    a=[obj for obj in dir(test) if not obj.startswith('__')]
    print(a)

classroom/templates/classroom/analyze.html
<html>
    <head>
        <title>Test</title>
    </head>

    <body>
        

classroom/templates/classroom/assignment_submit.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} Home {% endblock title %}

{% block content %}
<div class="row m-2">
    <div class="col-lg-8">
      <div class="row">
        <h3 class="text-primary">{{ assignment.title }}</h3>
        <div class="dropdown no-arrow ml-auto">
          <a class="btn btn-circle dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v fa-sm fa-fw text-dark"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
            <div class="dropdown-header">Dropdown Header:</div>
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </div>
      </div>
      <p class="text-muted">{{ assignment.created_by.username }} {{ assignment.created_at }}</p>
      <div class="row">
        <p class="text-dark font-weight-bold">{{ assignment.marks }} points</p>
        <p class="ml-auto text-dark font-weight-bold">Due {{ assignment.due_date }}</p>
      </div>
      <hr>
      <p>{{ assignment.description }}</p>
      <div class="row">
        {% for resource in assignment.resources %}
        <div class="col-6">
            <div class="card mb-3 ml-2">
                <div class="row no-gutters">
                    <div class="col-md-4">
                    <img src="{{ resource.files.url  }}" class="card-img img-fluid d-none d-lg-block" alt="...">
                    </div>
                    <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title "><a target="_blank" href="{{ resource.files.url  }}">{{ resource.filename }}...</a>
                        </h5>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    </div>

    <!-- The Submit cards -->
    <div class="col-lg-4">
      <div class="card p-4 m-3 shadow">
        
        <div class="row">
          <h4 class="text-primary">Your Work</h4>
              {% if submitted_assignment %}

                {% if submitted_assignment.turned_in %}
                <p class="ml-auto text-success">
                    Turned In
                </p>  
                      
                {% else %}
                <p class="ml-auto text-success">
                    Assigned
                </p>
                {% endif %}
              {% else %}
                <p class="ml-auto text-success">
                    Assigned
                </p>
              {% endif %}

        </div>
        {% if submitted_assignment and submitted_assignment.is_reviewed %}
            <div >

              <p class="ml-auto text-secondary">
                Graded : 
                {{ submitted_assignment.grade }}
              </p>
            </div>
        {% endif %}
        {% if submitted_assignment %}
            {% if assignment_files %}
                <p>Submitted files</p>
                {% for file in assignment_files %}
                  <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{{ file.files.url }}">{{ file.filename }}</a>
                        <form action="{% url 'classroom:unsubmit_file' file.pk %}" method="post">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-circle">X</button>
                        </form>
                    </li>
                  </ul>
                {% endfor %}
            {% endif %}
            {% if not submitted_assignment.turned_in %}
                <form action="{% url 'classroom:assignment_submit' assignment.pk %}" method="post" enctype='multipart/form-data'>
                  {% csrf_token %}
                  {{ form | crispy }}
                  <button type="submit" class="btn btn-outline-dark btn-block m-1">
                      <i class="fa fa-plus" aria-hidden="true"></i> Add or create
                  </button>
                </form>
                <form action="{% url 'classroom:turnin' assignment.pk %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-primary btn-block m-1">Mark as done</button>
                </form>
            {% else %}
                <form action="{% url 'classroom:unsubmit' assignment.pk %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-outline-dark btn-block m-1">Unsubmit</button>
                </form>
            {% endif %}
        {% else %}
            <form action="{% url 'classroom:assignment_submit' assignment.pk %}" method="post"  enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-outline-dark btn-block m-1">
                    <i class="fa fa-plus" aria-hidden="true"></i> Add or create
                </button>
            </form>
            <form action="{% url 'classroom:turnin' assignment.pk %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary btn-block m-1">Mark as done</button>
            </form>
        {% endif %}

      </div>

      <div class="card p-1 m-lg-3 m-md-1 shadow">
        <div class="mb-1 mt-3 ml-3 mr-1">
          {% for comment in assignment.comments %}
            {% if is_teacher or comment.user == request.user  %}
            <div class="d-flex flex-row">
                  <img src="{{ comment.user.profile.image.url }}" width="35" height="35" alt="..." class="rounded-circle mr-2">
                  <p class='ml-3'><strong>{{ comment.user }}</strong>: {{ comment.comment_text}}</p>
              </div>
            {% endif %}
          {% endfor %}
        </div>
      <div class="card-body">
          <form  action="{% url 'comments:private_comment' assignment.pk %}" method="post">
              <div class="input-group">
                <img src="{{ request.user.profile.image.url }}" width="35" height="35" alt="..." class="rounded-circle ml-2 mr-2">
                  {% csrf_token %}
                  {{ private_comment_form.comment_text|attr:"class:form-control rounded-pill"|attr:"placeholder:Add a private comment" }}
                  <div class="input-group-append">
                      <button class=" btn btn-circle" type="submit" id="button-addon2"><i class="fas fa-angle-double-right"></i></button>
                  </div>
              </div>
          </form>
      </div>
      </div>
</div>
{% endblock content %}

classroom/templates/classroom/home.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %} Home {% endblock title %}

{% block content %}
<!-- Page Heading -->
<h1 class="h3 mb-4 text-gray-800">Classrooms</h1>
<!-- ROW  -->
<div class="row">
    <!-- COL -->
    {% for classroom in classrooms %}
    <div class="col-lg-3 col-md-4 col-sm-1">
        <!-- CARD -->
        <div class="card border-bottom-primary shadow mb-4">
            <div class="card-header py-3">
                <a href="{% url 'classroom:open_classroom' classroom.id %}">
                    <h6 class="m-0 font-weight-bold text-primary">{{ classroom.name }}</h6>
                </a>
            </div>
            <a href="#!">
                <div class="card-body">
                    <div class="text-center">
                    <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="{% static 'mainapp/img/undraw_posting_photo.svg' %}" alt="">
                    </div>
                    <p class="text-secondary">{{ classroom.description }}</p>
                </div>
            </a>
        </div>
        <!-- END CARD -->
    </div>
    <!-- END COL -->
    {% endfor %}
</div>
<!-- END ROW -->

<!-- Modal Create Class -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Create Class</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <form action="{% url 'classroom:create_classroom' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="exampleInput">Class Name</label>
                        {{ classroom_form.name|attr:'class: form-control'|attr:'placeholder:Enter Classname' }}
                    </div>
                    <div class="form-group">
                        <label for="exam">Description</label>
                        {{ classroom_form.description|attr:'class: form-control'|attr:'placeholder:Enter Description' }}
                    </div>
                </div>
            
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Create Classroom</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal Join Class -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Join Class</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'classroom:join_classroom' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                        <div class="form-group">
                        <label for="exampleInput">{{ join_classroom_form.code.label }}</label>
                        {{ join_classroom_form.code|attr:'class: form-control'|attr:'placeholder:Enter Class Code' }}
                        <small id="Help" class="form-text text-muted">Ask your teacher for the class code, then enter it here.</small>
                        </div>
                    <ul><h5>To sign in with a class code</h5>
                        <li>Use an authorized account</li>
                        <li>Use a class code with 5-7 letters or numbers, and no spaces or symbols</li>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Join Classroom</button>
                    </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

classroom/templates/classroom/student_work.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} Home {% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h3>{{ assignment.title }}</h3>
        </div>
        <div class="col-lg-12">
        <ul class="navbar-nav">
            <div class="row">
                <li class="nav-item ml-2">
                    <h1>{{ assignment.total_turned_in }}</h1>
                    <small class='text-success'>Turned in</small>
                </li>
                <li class="nav-item ml-4">
                    <h1>{{ assignment.total_missing }}</h1>
                    <small class='text-danger'>Missing</small>
                </li>
            </div>
        </ul>
        </div>
    </div>

    <!-- Cards -->
    <div class="row">
        <div class="dropdown">
            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Assigned
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">All</a>
                <a class="dropdown-item" href="#">Turned in</a>
                <a class="dropdown-item" href="#">Graded</a>
            </div>
        </div>
    </div>



    <!-- Cards -->

    <div class="row">
        {% for ass in assignment.submitted_assignments %}
            <div class="col-lg-3 m-2 ">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-row">
                            <img src="{{ ass.user.profile.image.url }}" width="35" height="35" alt="..." class="rounded-circle mr-2 mb-2 float-left">
                            <p class="pt-2">{{ ass.user.username }}</p>
                            
                            <a class="btn btn-circle ml-auto" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v fa-sm fa-fw text-dark"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'assignments:grade' assignment.pk %}">Grade Student</a>
                                <a class="dropdown-item" href="{% url 'assignments:analyze' assignment.pk %}">Analyze Code</a>
                            </div>
                        </div>
                        
                        {% if ass.file_count >= 1 %}
                            <img class = "img-fluid" src="{{ ass.first_file_url }}" alt="" srcset="">
                        {% endif %}
                        <div class="mt-1">
                            <a href="#" class="card-link">{{ ass.file_count }}</a>
                            {% if ass.turned_in %}
                                <a href="#" class="card-link text-success">Turned In</a>
                            {% else %}
                                <a href="#" class="card-link text-danger">Missing</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}