classroom/urls.py
from django.urls import path 
from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create_classroom, name = 'create_classroom'),
    path('join/', views.join_classroom, name = 'join_classroom'),
    path('open/<int:pk>/', views.open_classroom, name = 'open_classroom'),
    path('<int:pk>', views.delete_classroom, name = 'delete_classroom'),
    path('<int:pk>/members', views.members, name = 'members_classroom'),
    path('assignment/<int:pk>/student_work', views.student_work, name = 'student_work'),
    path('assignment/create', views.assignment_create, name = 'assignment_create'),
    path('assignment/<int:pk>', views.assignment_submit, name = 'assignment_submit'),
    path('assignment/<int:pk>/turnin/', views.turnin, name = 'turnin'),
    path('assignment/<int:pk>/unsubmit/', views.unsubmit, name = 'unsubmit'),
    path('assignment/<int:pk>/unsubmit_file/', views.unsubmit_file, name = 'unsubmit_file'),
    path('todo/', views.todo, name = 'todo'),
    path('toreview/', views.toreview, name = 'toreview'),
    path('<int:pk>/classwork/', views.classwork, name = 'classwork'),
    path('analyze/', views.analyze, name='analyze')
]

finecode/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('comments', include('comments.urls')),
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
    path('', include('landingpage.urls')),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('assignments/', include('assignments.urls')),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(
        template_name = 'users/password_reset.html'),
        name = 'password_reset'
    ),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'),
        name = 'password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
    ),
        name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
    ),
      name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path 
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/<int:pk>/', views.create_post, name='create_post'),
    path('analyze/', views.analyze, name='analyze')
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings

from . import views

app_name= 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"),name="login"),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},name="logout"),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

finecode/templates/partials/_alerts.html
{% if messages %}
  {% for message in messages %}
    <div id="message" class="container">
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error: 
          {% else %}
            {{ message.tags|title }}
          {% endif %}
        </strong>
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}

finecode/templates/partials/_footer.html
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Website 2020</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

finecode/templates/partials/_head.html
{% load static %}


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
  
    
  
    <!-- Custom fonts for this template-->
    <link href="{% static 'mainapp/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  
    <!-- Custom styles for this template-->
    <link href="{% static 'mainapp/css/sb-admin-2.min.css' %}" rel="stylesheet">
    
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{% static 'mainapp/css/styles.css' %}">


     <!-- Bootstrap core JavaScript-->
    <script src="{% static 'mainapp/vendor/jquery/jquery.min.js' %}" defer></script>
    <script src="{% static 'mainapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}" defer></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'mainapp/vendor/jquery-easing/jquery.easing.min.js' %}" defer></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'mainapp/js/sb-admin-2.min.js' %}" defer></script>

    <script src="{% static 'mainapp/js/script.js' %}" defer></script>

    {% if 'todo' in request.path %}
        <script src="{% static 'mainapp/js/todo.js' %}" defer></script>
    {% endif %}

finecode/templates/partials/_logout_modal.html
  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'users:logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

finecode/templates/partials/_sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'classroom:home' %}">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-book-open"></i>
      </div>
      <div class="sidebar-brand-text mx-3"> FineCode   </div>
    </a>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'classroom:home' %}">
        <i class="fas fa-fw fa-cog"></i>
        <span>Classrooms</span>
      </a>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:todo' %}" >
        <i class="fas fa-fw fa-wrench"></i>
        <span>To Do</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:toreview' %}" >
        <i class="fas fa-fw fa-wrench"></i>
        <span>To Review</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:assignment_create' %}">
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Create Assignment</span></a>
    </li>

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

  </ul>
  <!-- End of Sidebar -->

finecode/templates/partials/_topbar.html
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>


    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

      <!-- Nav Item - Search Dropdown (Visible Only XS) -->
      <li class="nav-item dropdown no-arrow d-sm-none">
        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-search fa-fw"></i>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
          <form class="form-inline mr-auto w-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      {% if request.path == '/classroom/' %}
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="text-dark font-weight-bold">&#43;</span>
          </a>
          <!-- Dropdown - User Information -->
          <!-- Button trigger modal -->
          <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
            <a class="dropdown-item" data-toggle="modal" data-target="#exampleModalCenter" href="#">
              Create Room
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" data-toggle="modal" data-target="#exampleModal" href="#">
              Join Room
            </a>
          </div>
        
        </li>
      {% endif %}

    
      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.username }}</span>
          <img class="img-profile rounded-circle" src="{{ request.user.profile.image.url }}">
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="{% url 'users:profile' %}">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Profile
          </a>
          <a class="dropdown-item" href="#">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Settings
          </a>
          <a class="dropdown-item" href="#">
            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
            Activity Log
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
          </a>
        </div>
      </li>

    </ul>

  </nav>
  <!-- End of Topbar -->